[phases.setup]
nixPkgs = ["nodejs_20", "npm", "python3", "gcc", "gnumake", "pkg-config"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run seed"]

[start]
cmd = "cd backend && npm run seed && npm start"
